sudo: required
services:
 - docker

script:
 - docker build -t supattra/php-slim-composer .

after_success:
# login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images to docker hub
 - docker push supattra/php-slim-composer

deploy:
 provider: elasticbeanstalk
 region: us-east-1
 app: activity-in-la
 env: activity-in-la
 bucket_name: elasticbeanstalk-us-east-1-825369533922
 bucket_path: activity-in-la
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
