sudo: required
services:
 - docker

script:
 - docker build -t supattra/php-slim-composer .

after_success:
# login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images to docker hub
 - docker push supattra/php-slim-composer

deploy:
 provider: elasticbeanstalk
 region: us-east-1
 app: php-slim-docker
 env: Php-env
 bucket_name: elasticbeanstalk-us-east-1-545794717773
 bucket_path: php-slim-docker
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
